spring:
  application:
    name: store
  jwt:
    secret: ${JWT_SECRET}
    refreshTokenExpiration: 604800
    accessTokenExpiration: 7200 #2h
  data:
    redis:
      host: localhost
      port: 6379
stripe:
  secretKey: ${STRIPE_API_KEY}
  webhookSecretKey: ${STRIPE_WEBHOOK_SECRET}
  webUrl: http://localhost:4242