spring:
  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: root
    password: MyPassword!
  jpa:
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
stripe:
  webUrl: http://localhost:4242